project_id = "ellnbnxapuldtcaxtyou"

[functions.generate-image]
verify_jwt = false

[functions.edit-image]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false
