import { useEffect, useState } from "react";
import { useParams, Link, useNavigate } from "react-router-dom";
import { SEO } from "@/components/SEO";
import { supabase } from "@/integrations/supabase/client";
import { SitemapTree } from "@/components/SitemapTree";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { seedSitemaps } from "@/data/seedSitemaps";
import { Footer } from "@/components/Footer";
import { MainNavigation } from "@/components/platform/MainNavigation";
import { FileText, Layers, BarChart3, AlertTriangle, TreePine, ArrowRight } from "lucide-react";

const PublicSitemap = () => {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSitemap = async () => {
      // Check seed data first
      const seed = seedSitemaps.find(s => s.slug === slug);
      if (seed) {
        setData({
          domain: seed.domain,
          title: seed.title,
          description: seed.description,
          total_pages: seed.totalPages,
          max_depth: seed.maxDepth,
          top_level_sections: seed.topLevelSections,
          largest_cluster: seed.largestCluster,
          largest_cluster_size: seed.largestClusterSize,
          orphan_pages: seed.orphanPages,
          sitemap_data: seed.tree,
        });
        setLoading(false);
        return;
      }

      // Check database
      const { data: dbData } = await supabase
        .from("published_sitemaps")
        .select("*")
        .eq("slug", slug)
        .maybeSingle();

      if (dbData) setData(dbData);
      setLoading(false);
    };
    fetchSitemap();
  }, [slug]);

  if (loading) {
    return (
      <main className="min-h-screen bg-background p-8">
        <div className="max-w-4xl mx-auto space-y-4">
          <Skeleton className="h-10 w-2/3" />
          <Skeleton className="h-6 w-1/2" />
          <div className="grid grid-cols-5 gap-4">
            {[1,2,3,4,5].map(i => <Skeleton key={i} className="h-24" />)}
          </div>
          <Skeleton className="h-64 w-full" />
        </div>
      </main>
    );
  }

  if (!data) {
    return (
      <main className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-2">Sitemap Not Found</h1>
          <p className="text-muted-foreground mb-4">This sitemap hasn't been generated yet.</p>
          <Button asChild>
            <Link to="/analyzer">Analyze a Website</Link>
          </Button>
        </div>
      </main>
    );
  }

  // Related sitemaps
  const related = seedSitemaps
    .filter(s => s.slug !== slug)
    .sort(() => Math.random() - 0.5)
    .slice(0, 8);

  const stats = [
    { label: "Total Pages", value: data.total_pages, icon: FileText },
    { label: "Navigation Depth", value: `${data.max_depth} Levels`, icon: Layers },
    { label: "Top Sections", value: data.top_level_sections, icon: TreePine },
    { label: "Largest Cluster", value: `${data.largest_cluster} (${data.largest_cluster_size})`, icon: BarChart3 },
    { label: "Orphan Pages", value: data.orphan_pages, icon: AlertTriangle },
  ];

  // JSON-LD for SEO
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: `${data.domain} Website Structure – Visual Sitemap`,
    description: data.description || `Explore the website architecture and visual sitemap of ${data.domain}.`,
    url: `https://no-edit.lovable.app/sitemap/${slug}`,
    mainEntity: {
      "@type": "WebSite",
      name: data.domain,
      url: `https://${data.domain}`,
    },
    breadcrumb: {
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: "https://no-edit.lovable.app/" },
        { "@type": "ListItem", position: 2, name: "Sitemap Library", item: "https://no-edit.lovable.app/sitemaps" },
        { "@type": "ListItem", position: 3, name: `${data.domain} Sitemap`, item: `https://no-edit.lovable.app/sitemap/${slug}` },
      ],
    },
  };

  return (
    <>
      <SEO
        title={`${data.domain} Website Structure – Visual Sitemap | EPIC`}
        description={data.description || `Explore the website architecture and visual sitemap of ${data.domain} generated by EPIC. ${data.total_pages} pages, ${data.max_depth} levels deep.`}
      />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      
      <MainNavigation
        activeTab="home"
        onTabChange={(tab) => {
          if (tab === "home") navigate("/");
        }}
      />
      
      <main className="min-h-screen bg-background pt-14">
        <div className="max-w-5xl mx-auto px-6 py-12 space-y-10">
          {/* Breadcrumb */}
          <nav className="flex items-center gap-2 text-sm text-muted-foreground" aria-label="Breadcrumb">
            <Link to="/" className="hover:text-foreground transition-colors">Home</Link>
            <span>/</span>
            <Link to="/sitemaps" className="hover:text-foreground transition-colors">Sitemap Library</Link>
            <span>/</span>
            <span className="text-foreground">{data.domain}</span>
          </nav>

          {/* Header */}
          <header>
            <h1 className="text-3xl font-bold mb-2">Visual Sitemap of {data.domain}</h1>
            <p className="text-muted-foreground max-w-2xl">
              The website {data.domain} is structured into {data.top_level_sections} major sections
              with a maximum navigation depth of {data.max_depth} levels. The largest content cluster
              is "{data.largest_cluster}" with {data.largest_cluster_size} pages.
            </p>
          </header>

          {/* Stats */}
          <section>
            <h2 className="text-xl font-semibold mb-4">Structure Report</h2>
            <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
              {stats.map(stat => (
                <Card key={stat.label} className="p-4 text-center">
                  <stat.icon className="h-5 w-5 mx-auto mb-2 text-primary" />
                  <div className="text-xl font-bold">{stat.value}</div>
                  <div className="text-xs text-muted-foreground">{stat.label}</div>
                </Card>
              ))}
            </div>
          </section>

          {/* Tree */}
          <section>
            <h2 className="text-xl font-semibold mb-4">Interactive Visual Sitemap</h2>
            <SitemapTree nodes={data.sitemap_data} />
          </section>

          {/* CTA */}
          <section className="text-center py-8 border-t border-border">
            <h2 className="text-2xl font-bold mb-2">Analyze your own website structure with EPIC</h2>
            <p className="text-muted-foreground mb-4">
              Get a visual sitemap, architecture report, and UX insights — free.
            </p>
            <Button asChild size="lg" className="gap-2">
              <Link to="/analyzer">
                Generate Your Sitemap <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          </section>

          {/* Related */}
          <section>
            <h2 className="text-xl font-semibold mb-4">Explore More Website Structures</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {related.map(s => (
                <Link
                  key={s.slug}
                  to={`/sitemap/${s.slug}`}
                  className="block p-3 rounded-lg border border-border hover:border-primary/50 hover:bg-accent/30 transition-colors"
                >
                  <div className="font-medium text-sm">{s.domain}</div>
                  <div className="text-xs text-muted-foreground">{s.totalPages} pages · {s.maxDepth} levels</div>
                </Link>
              ))}
            </div>
          </section>
        </div>
        <Footer />
      </main>
    </>
  );
};

export default PublicSitemap;
