// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ellnbnxapuldtcaxtyou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbG5ibnhhcHVsZHRjYXh0eW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMDY1NTQsImV4cCI6MjA3NDc4MjU1NH0.EofIPXAJT6h2py6K93yBGxj12-BSOIkGzSyoXQTqwtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});